### ISSUE TITLE
Hello author, can you share your data file, I will learn from it

### ISSUE THREAD

**Issue by GEM123668** [Siliam/social_network_analysis#1]
Hello author, can you share your data file, I will learn from it

**Comment by Siliam** [comment]
Hello @GEM123668 
I have added the examples data. 
If you wanna learn more about _Social Network Analysis_, check the following course (it's where I found the examples): [Applied Social Network Analysis in Python](https://www.coursera.org/learn/python-social-network-analysis).

**Comment by GEM123668** [comment]
great！
